/**
 * Generate the Career Agent's coding and system-design question catalog from
 * the exact pools used by CompanyQuestPage.
 *
 * Keeping this generated server copy means the model can only ask a technical
 * question that the browser can open with the same stable challenge id.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getCodingPool } from '../src/lib/codingChallenges';
import { buildSystemDesignBrief, getSystemDesignPool } from '../src/lib/companyQuests';
import type { LocalInterviewGuide } from '../src/lib/localInterviewGuideCore';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const guideDirectory = join(root, 'data', 'interview-guides');
const outputPath = join(root, 'functions', 'src', 'agentPracticeCatalog.generated.ts');

const guides = readdirSync(guideDirectory)
  .filter((filename) => filename.endsWith('.json') && !filename.startsWith('_'))
  .map((filename) => JSON.parse(readFileSync(join(guideDirectory, filename), 'utf8')) as LocalInterviewGuide)
  .sort((a, b) => a.slug.localeCompare(b.slug));

const codingQuestions: Record<string, { id: string; title: string; question: string }> = {};
const systemDesignQuestions: Record<string, Record<string, { id: string; title: string; question: string }>> = {};

const catalog = Object.fromEntries(guides.map((guide) => {
  const coding = getCodingPool(guide).map((challenge) => {
    codingQuestions[challenge.id] = {
      id: challenge.id,
      title: challenge.title,
      question: `${challenge.title}: ${challenge.description}`,
    };
    return challenge.id;
  });
  const designForGuide: Record<string, { id: string; title: string; question: string }> = {};
  const systemDesign = getSystemDesignPool(guide).map((pattern) => {
    const brief = buildSystemDesignBrief(guide, pattern);
    designForGuide[pattern.id] = {
      id: pattern.id,
      title: pattern.title,
      question: brief.challenge,
    };
    return pattern.id;
  });
  systemDesignQuestions[guide.slug] = designForGuide;
  return [guide.slug, { company: guide.company, coding, systemDesign }];
}));

const output = `// Generated by scripts/generate-agent-practice-catalog.ts. Do not edit manually.\n\n`
  + `export interface AgentPracticeQuestion {\n`
  + `  id: string;\n`
  + `  title: string;\n`
  + `  question: string;\n`
  + `}\n\n`
  + `export interface AgentPracticeCatalogEntry {\n`
  + `  company: string;\n`
  + `  coding: readonly string[];\n`
  + `  systemDesign: readonly string[];\n`
  + `}\n\n`
  + `export const AGENT_CODING_QUESTIONS: Readonly<Record<string, AgentPracticeQuestion>> = `
  + `${JSON.stringify(codingQuestions, null, 2)};\n\n`
  + `export const AGENT_SYSTEM_DESIGN_QUESTIONS: Readonly<Record<string, Readonly<Record<string, AgentPracticeQuestion>>>> = `
  + `${JSON.stringify(systemDesignQuestions, null, 2)};\n\n`
  + `export const AGENT_PRACTICE_CATALOG: Readonly<Record<string, AgentPracticeCatalogEntry>> = `
  + `${JSON.stringify(catalog, null, 2)};\n`;

writeFileSync(outputPath, output);
console.log(`Generated ${guides.length} Agent practice catalogs → ${relative(root, outputPath)}`);
